pCDC_This CDC_This = (pCDC_This)MAIN_OFFSET_INTERFACE_OFFSET;
pCDCSetTextColor MU_SetTextColor = (pCDCSetTextColor)MAIN_OFFSET_SET_TEXT_COLOR_OFFSET;
pCDC00420120 MU_SetFont = (pCDC00420120)MAIN_OFFSET_SET_FONT_OFFSET;
pCDCTabbedTextOut MU_TabbedTextOut = (pCDCTabbedTextOut)MAIN_OFFSET_TEXT_OUT;
pCDC004200F0 MU_4200F0 = (pCDC004200F0)MAIN_OFFSET_INTERFACE_UNK_OFFSET;
pMU_BindTexture MU_BindTexture = (pMU_BindTexture)MAIN_OFFSET_BIND_TEXTURE;